services:
  hugo:
    build: .
    container_name: dasc-hugo
    ports:
      - "1313:1313"
    volumes:
      - .:/root/src
    environment:
      - HUGO_ENV=development
    restart: unless-stopped
    tty: true
    stdin_open: true
