baseURL = 'https://dasc-lab.github.io/'
languageCode = 'en-us'
title = 'DASC Lab UMich'
buildFuture = true

[permalinks]
  blog = "/:filename/"

[taxonomies]
# person = "people"


# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "People"
    url = "/people/"
    weight = 2
  [[menu.main]]
    name = "Papers"
    url = "/papers/"
    weight = 3
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 4
  [[menu.main]]
    name = "Code"
    url = "/code/"
    weight = 5
  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 100

[params]
  dateFormat = "Jan 2, 2006"
  homeText = "Distributed Autonomous Systems and Control Lab"
